pipeline {
    agent none
    stages {
        stage('Install dep scan and build') {
            agent {
                docker { image 'node:18.19.0-alpine3.19' }
            }
            steps {
                dir('frontend') {
                    sh 'npm install'
                    withSonarQubeEnv(installationName: 'sonarqube') {
                        sh 'npm sonar'
                    }
                    sh 'npm build'
                    stash includes: '**/dist/*', name: 'app'
                }
            }
        }
    }
}
