pipeline {
    agent none
    stages {
        stage('Install dep and build') {
            agent {
                docker { image 'node:18.19.0-alpine3.19' }
            }
            steps {
                dir('frontend') {
                    sh 'npm install'
                    sh 'npm run build'
                    stash includes: '**/dist/*', name: 'app'
                }
            }
        }
        stage('scann') {
            agent { label 'java' }
            environment {
                SCANNER_HOME = tool 'sonarqube'
            }
            steps {
                dir('frontend') {
                    withSonarQubeEnv(installationName: 'sonarqube') {
                        sh "${SCANNER_HOME}/bin/sonar-scanner"
                    }
                }
            }
        }
        stage('publish') {
            agent {
                docker { image 'node:18.19.0-alpine3.19' }
            }
            steps {
                dir('frontend') {
                    withCredentials([string(credentialsId: 'npm_token', variable: 'NEXUS_SECRET')]) {
                        sh 'npm publish'
                    }
                }
            }
        }
    }
}
