version: '3.8'

services:
  frontend:
    image: frontend:latest
    environment:
      BACKEND_URL: 'http://backend:8080'
    ports:
      - 8080:80
  
  backend:
    image: backend:latest
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db:5432/postgres'
    expose:
      - "8080"
    depends_on:
      - db
    
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql:
  postgresql_data: